### ISSUE TITLE
creation of a new Author route

### ISSUE THREAD

**Issue by guenterh** [linked-swissbib/vufind#1]
Hallo Günter

Ich habe mal probiert den Such-URL von "Exploration/Search" nach "Exploration/Author" umzubenennen.

Diese Stelle habe ich im Code gefunden:

https://github.com/linked-swissbib/vufind/blob/vfsb/linked/module/LinkedSwissbib/config/module.config.php#L94

Das umzubenennen hatte allerdings keinen sichtbaren Effekt.

Als weitere Massnahme habe ich das Verzeichnis local/cache/ gelöscht und in den Development Modus ( https://github.com/linked-swissbib/vufind/blob/vfsb/linked/local/httpd-swissbib.conf#L49 ) gewechselt. Das hat aber nichts Sichtbares bewirkt.

Als Fehlermeldung erhielt ich:

An error has occurred
Page not found.
Message: error-controller-cannot-dispatch

Siehst du gerade, wo ich da noch ansetzen müsste?

Gruss

Lukas

**Comment by guenterh** [comment]
@ltog @ThomasWeinhold 
Hallo Lukas
ich habe einen commit eingestellt
https://github.com/linked-swissbib/vufind/commit/8483ad80d058414fecba344de7ebae4785035b61
Die Route ist nun benutzbar. 
Was mir auffiel und im Moment nicht gefällt
   'controllers' => [
        'invokables' => [
            'exploration'    => 'LinkedSwissbib\Controller\ElasticsearchController',
            'inference'    => 'LinkedSwissbib\Controller\SparqlController',
Ich werde mir das nächste Woche ansehen - nicht vor Dienstag.

Viele Grüsse aus Weisweiler (zwischen Aachen und Köln)

Günter

**Comment by ltog** [comment]
Hallo @guenterh 

Eine gute Idee, die Issues dafür zu benutzen! :-)

Habe ich richtig verstanden, dass der Funktionsname `authorAction()` und die Datei `author.phtml` zwingend den Namen der Action (hier `Author`) enthalten müssen und dann auch automatisch richtig ausgeführt werden?

**Comment by ltog** [comment]
@guenterh: Was in https://github.com/linked-swissbib/vufind/issues/1#issuecomment-120329954 gefällt dir nicht?

**Comment by ltog** [comment]
Bei Commit https://github.com/linked-swissbib/vufind/commit/f5b785cd028906599c1558f69b4010b83aa4cb5d habe ich mich in der Commit-Message vertan. Die Änderung bezog sich auf Issue #2.
