### ISSUE TITLE
Recursive Elasticsearch Query

### ISSUE THREAD

**Issue by ltog** [linked-swissbib/vufind#10]
In some cases we need to do more than one query to Elasticsearch in order to get all information we need.

Example: When looking at one Work, we would like to display information (e.g. the year (`dct:issued`)) for each instance = bibliographicResource. Elasticsearch doesn't allow to retrieve this information in one query. Therefore we need to modify the code to do two Elasticsearch/HTTP Requests.

**Comment by ltog** [comment]
Here's a list of useful information I found:
- https://www.youtube.com/watch?v=8InrSNbt1Sk (after about the middle, when the presentation is finished, it gets somewhat less relevant)
- [English slides as used in the video](https://github.com/linked-swissbib/vufind/files/86944/VuFind-Anwendertreffen-workshop1-maus.pdf)
- [Original german slides](https://github.com/linked-swissbib/vufind/files/86941/search.pdf)
- Sequence diagram of a search: ![vf2-search-sequence](https://cloud.githubusercontent.com/assets/4726277/12258245/6f6ec36a-b90d-11e5-90b5-988a991aa065.png)
- https://vufind.org/wiki/development:architecture:search_service

**Comment by guenterh** [comment]
Hi Lukas,

thanks for heading forward on this topic.

Instead of writing quite a lot of comments right now, could we start a call on this topic (either skype or good old telephone) in the course of this week?

Günter

**Comment by ltog** [comment]
At the newly created https://github.com/linked-swissbib/vufind/blob/69f43411ad4b25a5bbff0a1a3764b46969090dde/module/LinkedSwissbib/src/LinkedSwissbib/Search/Elasticsearch/RecursiveSearchListener.php#L69 (Branch: `recursive_search`) we have access to the search results of a (first-level) ES search. These could be enhanced now by a second ES query.

@guenterh : Do you like this approach?

**Comment by ltog** [comment]
Short summary of the phone call with Günter: I will continue implementing the recursive search as planned.

**Comment by ltog** [comment]
Here is a screenshot of a `ElasticsearchRDF` record in https://github.com/linked-swissbib/vufind/blob/69f43411ad4b25a5bbff0a1a3764b46969090dde/module/LinkedSwissbib/src/LinkedSwissbib/Search/Elasticsearch/RecursiveSearchListener.php#L71 .

![elasticsearchrdf-record](https://cloud.githubusercontent.com/assets/4726277/12291634/b3d612ca-b9e8-11e5-8653-f41fa108d12e.PNG)

Corresponding ES query is:

```
GET /testsb/work/_search
{
"query": {
"filtered": {
"filter": {
"bool": {
  "must": {"term": {"@id": "http://data.swissbib.ch/work/043422853"}}
}
}
}
}
}
```

My plan is to extend such a record with additional arrays (e.g. `dct:issued`) identical in style as the existing `bf:hasInstance` and `dct:title`.
