### ISSUE TITLE
implement a configured search

### ISSUE THREAD

**Issue by guenterh** [linked-swissbib/vufind#4]
The ES Backend has to support a configured search comparable to the default SOLR target supported by VuFind
# some of the requirements
- consider default Options and Params 
- use one of the ES clients (Elasticsearch or Elastica)
- use the features of ES Query DSL and ES Filter DSL to provide the content for the linked-swissbib uses cases
- the used ES Backend types should be comparable to the ones delivered for SOLR by VuFind because it should be easy for people already familiar with the SOLR Backend to integrate it in their own code

**Comment by guenterh** [comment]
@ltog @ThomasWeinhold 
Hi Lukas and Thomas

a first implementation is now available as part of a new branch 
https://github.com/linked-swissbib/vufind/commits/feature/configuredSearch

Basically it supports a configuration for the fields used in the request against ES. For this a new search specification similar to the one we use in SOLR is available.
https://github.com/linked-swissbib/vufind/blob/feature/configuredSearch/local/config/vufind/searchspecsES.yaml
I'm still thinking about the layout of this configuration - so it's work in progress. 

In you local config.ini 
(directory local/config/vufind/config.ini)
a new setting should be done
[LinkedIndex]
hosts[]=sb-s2.swissbib.unibas.ch:8080
hosts[]=sb-s6.swissbib.unibas.ch:8080
hosts[]=sb-s7.swissbib.unibas.ch:8080

This has to be done by yourself because the local config.ini is not committed to GitHub

**Comment by ltog** [comment]
@guenterh : Do you mind if we add this file (and all future changes to the local/ directory) to Git?

**Comment by guenterh** [comment]
@ltog 
I added a template file (without any passwords and encryption keys) for the local config.ini we might use in our linked-swissbib project.
https://github.com/linked-swissbib/vufind/commit/0945d0e493ca697b463dfac77406967efcd1e8ec

At the moment it's in the branch I'm currently working on to include the ES php client. By now this branch isn't executable because I removed the Elastica client and updated to native Elasticsearch (dev) client which I'm going to use for our purposes. (Yesterday I talked with Nicolas Ruflin https://github.com/ruflin/Elastica about this topic in Zurich)
I exepect to provide a functional version at the end of this day. Then I think we should work together on this topic.

Günter

**Comment by guenterh** [comment]
@ltog @ThomasWeinhold 
Hi
the new branch is again runnable
https://github.com/linked-swissbib/vufind/commit/3ac3444856ab131a11fc1a77c88fe5e34476fc32
You could use it if you want.
I'm still working on it to improve the basic functionality
Günter
